#!/bin/sh

bin/php vendor/bin/phpcbf --standard=PSR12 ./src ./tests
bin/php vendor/bin/phpcs --standard=PSR12 ./src ./tests

bin/php vendor/bin/phpstan analyse --level=9 --memory-limit=256M ./src 
bin/php vendor/bin/phpstan analyse --level=9 --memory-limit=256M ./tests 

bin/phpunit --testsuite all