#!/bin/bash


function init_docker_userid_groupid() {
    USERID=$(id -u)
    export USERID
    GROUPID=$(id -g)
    export GROUPID
}

function build_docker_image() {
    docker compose build php
    docker build -t composer-multitenant docker/composer/
}

init_docker_userid_groupid

build_docker_image
