services:
    Phariscope\MultiTenant\Command\CreateTenantDatabaseCommand:
        tags: ['console.command']
        autowire: true
        autoconfigure: true

    Phariscope\MultiTenant\Command\CreateTenantSchemaCommand:
        tags: ['console.command']
        autowire: true
        autoconfigure: true