services:
    _defaults:
        autowire: true
        autoconfigure: true

    Phariscope\MultiTenant\:
        resource: '../src/'
        exclude:
            - '../src/Symfony/Kernel.php'

    Phariscope\MultiTenant\Command\CreateTenantDatabaseCommand:
        tags: ['console.command']
        autowire: true
        autoconfigure: true

    Phariscope\MultiTenant\Command\CreateTenantSchemaCommand:
        tags: ['console.command']
        autowire: true
        autoconfigure: true
